#!/usr/bin/env node

var robot = require("robotjs");
var fs = require('fs');
var filename = process.argv[2];
var fileToType;

fs.readFile(filename, 'utf8', function (err,data) {
  if (err) {
    return console.log(err);
  }
  fileToType = data.split("");
  writeCharacter();
});

function writeCharacter() {
   if (fileToType.length > 0) {
      let character = fileToType.shift();
      if (character == "\n") {
         robot.keyTap("enter");
      } else {
         robot.typeString(character);
      }
      setTimeout(writeCharacter,250);
   }      
}